#!/usr/bin/env bash

shopt -s nocasematch
# exit immediately if a command exits with a non-zero status
#set -e
# get base dir regardless of execution location
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ "$SOURCE" != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SOURCE=$([[ "$SOURCE" = /* ]] && echo "$SOURCE" || echo "$PWD/${SOURCE#./}")
basedir=$(dirname "$SOURCE")
gitcmd="git -c commit.gpgsign=false"
. "$basedir"/scripts/init.sh

paperstash() {
    STASHED=$(git stash)
}

paperunstash() {
    if [[ "$STASHED" != "No local changes to save" ]] ; then
        git stash pop
    fi
}

case "$1" in
    "rb" | "rbp" | "rebuild")
    (
        cd "$basedir"
        ./gradlew rebuildpatches
    )
    ;;
    "p" | "patch" | "apply")
    (
        cd "$basedir"
        ./gradlew applypatches
    )
    ;;
    "commit" | "c")
    (
        case "$2" in
            "s" | "server")
            type="Server"
            ;;
            "a" | "api")
            type="API"
            ;;
            *)
                echo "You must specify either the api or server."
            ;;
        esac
          if [ $type ]; then
            cd "$basedir/${FORK_NAME}-$type"
            $gitcmd add .
            $gitcmd commit -m "${@:3}"
            cd "$basedir"
            ./gradlew rebuildpatches
        fi
    )
    ;;
    "e" | "edit" ) # Courtesy Origami
        case "$2" in
            "s" | "server")
            type="server"
            ;;
            "a" | "api")
            type="api"
            ;;
            *)
                echo "You must edit either the api or server."
            ;;
        esac
        if [ $type ]; then
            cd "$basedir/${FORK_NAME}-$type"
            set -e
            case "$3" in
                "c" | "continue")
                (
                    $gitcmd add .
                    $gitcmd commit --amend
                    $gitcmd rebase --continue

                    cd "$basedir"
                    ./gradlew rebuildpatches
                )
                ;;
                *)
                    paperstash
                    $gitcmd rebase -i upstream/master
                    paperunstash
                ;;
            esac
        fi
    ;;
    "jar" | "paperclip")
    (
        cd "$basedir"
        ./gradlew createReobfPaperclipJar --stacktrace
    )
    ;;
    "d" | "de" | "deploy")
    (
        cd "$basedir"
        ./gradlew SemiVanilla-API:publish
    )
    ;;
    "r" | "root")
        cd "$basedir"
    ;;
    "a" | "api")
        cd "$basedir/${FORK_NAME}-api"
    ;;
    "s" | "server")
        cd "$basedir/${FORK_NAME}-server"
    ;;
    "build")
    (
        cd "$basedir"
        ./gradlew build --stacktrace
    )
    ;;
    "run" | "dev" | "rundev")
    (
        cd "$basedir"
        ./gradlew rundev
    )
    ;;
    "setup")
        if [[ -f ~/.bashrc ]] ; then
            NAME="SemiVanilla"
            if [[ ! -z "${2+x}" ]] ; then
                NAME="$2"
            fi
            (grep "alias $NAME=" ~/.bashrc > /dev/null) && (sed -i "s|alias $NAME=.*|alias $NAME='. $SOURCE'|g" ~/.bashrc) || (echo "alias $NAME='. $SOURCE'" >> ~/.bashrc)
            alias "$NAME=. $SOURCE"
            echo "You can now just type '$NAME' at any time to access the paper tool."
        fi
    ;;
    *)
        echo "${FORK_NAME} build tool command. This provides a variety of commands to build and manage the PaperMC build"
        echo "environment. For all of the functionality of this command to be available, you must first run the"
        echo "'setup' command. View below for details. For essential building and patching, you do not need to do the setup."
        echo ""
        echo " Normal commands:"
        echo "  * rb, rebuild  | Rebuild patches, can be called from anywhere."
        echo "  * p, patch     | Apply all patches on top of upstream without building it. Can be run from anywhere."
        echo "  * up, upstream | Build upstream, pass arg up to update upstream. Can be run from anywhere."
        echo "  * b, build     | Build API and Server but no deploy. Can be ran anywhere."
        echo "  * d, deploy    | Build and Deploy API jar and build Server. Can be ran anywhere."
        echo ""
        echo " These commands require the setup command before use:"
        echo "  * r, root      | Change directory to the root of the project."
        echo "  * a, api       | Move to the ${FORK_NAME}-API directory."
        echo "  * s, server    | Move to the ${FORK_NAME}-Server directory."
        echo "  * e, edit      | Use to edit a specific patch, give it the argument \"server\" or \"api\""
        echo "                 | respectively to edit the correct project. Use the argument \"continue\" after"
        echo "                 | the changes have been made to finish and rebuild patches. Can be called from anywhere."
        echo ""
        echo "  * setup        | Add an alias to .bashrc to allow full functionality of this script. Run as:"
        echo "                 |     . ./SemiVanilla setup"
        echo "                 | After you run this command you'll be able to just run 'SemiVanilla' from anywhere."
        echo "                 | The default name for the resulting alias is 'SemiVanilla', you can give an argument to override"
        echo "                 | this default, such as:"
        echo "                 |     . ./SemiVanilla setup example"
        echo "                 | Which will allow you to run 'example' instead."
    ;;
esac

unset -f paperstash
unset -f paperunstash
